'use client'
import Head from 'next/head';
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar';
import {store} from './store'
import {Provider} from 'react-redux'
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Nitesh Kumar portofolio',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <>
    <Head>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet" />
    </Head>
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
        {children}
          </Provider>
      </body>
    </html>
    </>
  )
}
